### ISSUE TITLE
Example 15:  Import static does not work, where may I find JRuleItemNames? 

### ISSUE THREAD

**Issue by uwejanssen19** [seaside1/jrule#137]
I tried to make a rule similar to example 15:

```
package org.openhab.automation.jrule.rules.user;

import static org.openhab.automation.jrule.generated.items.JRuleItemNames.Bureau_IR_group;
import org.openhab.automation.jrule.rules.JRuleLogName;
import org.openhab.automation.jrule.rules.JRuleName;
import org.openhab.automation.jrule.rules.JRuleWhenItemChange;
import org.openhab.automation.jrule.rules.event.JRuleItemEvent;

public class BureauGroupChange extends JRuleBase {
    public static final String MYRULECLASS = "BureauGroupChange";
    public static final String MYLOGNAME = MYRULECLASS + "_RULE";

    @JRuleName(MYRULECLASS)
    @JRuleLogName(MYLOGNAME)
    @JRuleWhenItemChange(item = Bureau_IR_group/*, memberOf = JRuleMemberOf.Items*/)
    public synchronized void groupMySwitchGroupChanged(JRuleItemEvent event) {
        final String memberThatChangedStatus = ((JRuleItemEvent) event).getMemberName();
        logInfo(MYLOGNAME + " {} changed to {}", memberThatChangedStatus, event.getState());
    }
}

```

The compiler complains:
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.297 s
[INFO] Finished at: 2023-02-23T19:47:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project openhabrules: Compilation failure: Compilation failure:
[ERROR] /p:/dokumente/uwe/garden-control/openhab/automation/jrule/openhabrules/src/main/java/org/openhab/automation/jrule/rules/user/BureauGroupChange.java:[4,59] Symbol nicht gefu
nden
[ERROR]   Symbol: Klasse JRuleItemNames
[ERROR]   Ort: Package org.openhab.automation.jrule.generated.items
[ERROR] /p:/dokumente/uwe/garden-control/openhab/automation/jrule/openhabrules/src/main/java/org/openhab/automation/jrule/rules/user/BureauGroupChange.java:[4,1] **Statischer Import
nur aus Klassen und Schnittstellen**
[ERROR] /p:/dokumente/uwe/garden-control/openhab/automation/jrule/openhabrules/src/main/java/org/openhab/automation/jrule/rules/user/BureauGroupChange.java:[18,33] Symbol nicht gef
unden
[ERROR]   Symbol: Variable Bureau_IR_group
[ERROR]   Ort: Klasse org.openhab.automation.jrule.rules.user.BureauGroupChange
[ERROR] -> [Help 1]
[ERROR]
```

- A simple Hello World example rule with a switch item is working.
Thus, my pom.xml seems to be o.k.
- A similar DSL rule is working
- I am running OH 3.3.0 under openhabian.
- Development is under Windows 11, VS Studio 1.75
- I made sure the local repo under <user>/.m2 contains the same jrule.jar and jrule-generated.jar as the one in /etc/openhab/
 

[pom.zip](https://github.com/seaside1/jrule/files/10822458/pom.zip)

**Comment by querdenker2k** [comment]
have you imported the generated jrule-jar like this:
```xml
<dependency>
    <groupId>org.openhab</groupId>
    <artifactId>openhab-generated</artifactId>
    <version>1.0.0</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/jrule-generated.jar</systemPath>
</dependency>
```

**Comment by uwejanssen19** [comment]
Thank you  for  your  proposal. I did not. Rather, i created  a  local  Repository and referred to it in my  pom.xml. This  worked  for the  first  example,  at least. Nevertheless the  jar  file  may  be  wong.How  can  i  check? Thanks  for helping meVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: "Robert D." ***@***.***> Datum: 23.02.23  22:03  (GMT+01:00) An: seaside1/jrule ***@***.***> Cc: uwejanssen19 ***@***.***>, Author ***@***.***> Betreff: Re: [seaside1/jrule] Example 15:  Import static does not work, where may I find JRuleItemNames?  (Issue #137) 
have you imported the generated jrule-jar like this:
<dependency>
    <groupId>org.openhab</groupId>
    <artifactId>openhab-generated</artifactId>
    <version>1.0.0</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/jrule-generated.jar</systemPath>
</dependency>

**Comment by querdenker2k** [comment]
Can the dependency (which you put manually in your m2-repo?) be resolved from maven?
Inside the jar must be this package: org.openhab.automation.jrule.generated

**Comment by uwejanssen19** [comment]
I think it is resolved- at least there is no error message. I also double checked if the jar files in the repo are identical. And I unpacked the jar files and made a full text search looking for JRuleItemNames.There is no such class.Thank you for your advice anyway.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: "Robert D." ***@***.***> Datum: 24.02.23  21:19  (GMT+01:00) An: seaside1/jrule ***@***.***> Cc: uwejanssen19 ***@***.***>, Author ***@***.***> Betreff: Re: [seaside1/jrule] Example 15:  Import static does not work, where may I find JRuleItemNames?  (Issue #137) 
Can the dependency (which you put manually in your m2-repo?) be resolved from maven?
Inside the jar must be this package: org.openhab.automation.jrule.generated

**Comment by uwejanssen19** [comment]
There must be a misunderstanding which lead to close the issue. I only stated that maven did not generate an error message in respect to jrule-generated.jar.Nevertheless the issue is still there and I have no idea how to proceed.Please help.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: "Robert D." ***@***.***> Datum: 25.02.23  07:11  (GMT+01:00) An: seaside1/jrule ***@***.***> Cc: uwejanssen19 ***@***.***>, Author ***@***.***> Betreff: Re: [seaside1/jrule] Example 15:  Import static does not work, where may I find JRuleItemNames?  (Issue #137) 
Closed #137 as completed.

**Comment by querdenker2k** [comment]
I thought so, that it was completely resolved. Well, when you compile the error still persists?
Have you installed the jar to your repo with _install:install-file_?
Isn't VS-Code showing an error?

**Comment by uwejanssen19** [comment]
Hello again,Thank you for continuing  the conversation. Yes, I still have a compilation error. And yes, I used install:install-file.As I already mentioned I did not find any occurrence of JRuleItemNames in neither  jrule.jar nor jrule-generated.jar.Md5sum of jrule-generated.jar is 11e5b0e864bfde2e57a3821c0e249b8fI also reinstalled the jrules addon in openhab.Might it be possible that example 15 is only working for a non released edition of the jrule addon?Maybe you can check if I have the right jar file.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: "Robert D." ***@***.***> Datum: 25.02.23  08:32  (GMT+01:00) An: seaside1/jrule ***@***.***> Cc: uwejanssen19 ***@***.***>, Author ***@***.***> Betreff: Re: [seaside1/jrule] Example 15:  Import static does not work, where may I find JRuleItemNames?  (Issue #137) 
I thought so, that it was completely resolved. Well, when you compile the error still persists?
Have you installed the jar to your repo with install:install-file?
Isn't VS-Code showing an error?

**Comment by querdenker2k** [comment]
If you attach the jar file i can check.

**Comment by seaside1** [comment]
What release are you using. The BETA15 will not work.
I'm about to build a new release but we had quite a lot of refactorings, but I'll do it shortly.

**Comment by seaside1** [comment]
[jrule-3.x.x-BETA16-prebuild.zip](https://github.com/seaside1/jrule/files/10830749/jrule-3.x.x-BETA16-prebuild.zip)


You will have to decompress it first.

**Comment by seime** [comment]
@uwejanssen19 did you test with the version from @seaside1 ?

**Comment by seaside1** [comment]
There is a new BETA16 release as well, so please try and update and see if you can get it to work.

**Comment by seime** [comment]
No response from reporter. Reopen if problem persist.
