### ISSUE TITLE
JRule PR42 Issues

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#43]
After the merge of pr42 I noticed you could not any longer load rules from source files (jar is possible)
Also the rules I had in my jar file would not trigger (cronbased and similar would trigger)
I rolled back JRuleCompiler and JRuleHandler and they started working again.

@seime  Let's try and sort out some issues before we build the next release

- Fix JRuleCompiler and JRuleHandler
- Fix Rule loading statistics so it works from both jar and source files

I'll update if I find more.

**Comment by seime** [comment]
Sorry for not getting back to you, been busy with other stuff. Will try to look at it before holidays.

**Comment by seaside1** [comment]
No worries busy with vacation myself 👍

**Comment by seime** [comment]
@seaside1 Could you provide a few examples of rule triggers that stopped working for you?

**Comment by seaside1** [comment]
I had a strange error in my rules, used sendCommand(_MyDimmer.ITEM, 100);
Had to change it to sendCommand(_MyDimmer.ITEM, new JRulePercentType(100));
Guess it was treated as a DecimalType.

**Comment by seime** [comment]
@seaside1  I pushed some more commits on #42 

- Fixed bug when an item was removed/deleted, no Items.java was generated and hence it would fail compilation
- Fixed bug where a new rule was created for an item/channel that previously was not used in any rules - and hence would not trigger (does this issue fit https://github.com/seaside1/jrule/issues/43#issuecomment-1188266404 ?)

- I could not see any issues with the statistics part, both rules in jar as well as Java source files are counted at least on my system
- Regarding https://github.com/seaside1/jrule/issues/43#issuecomment-1188315264 the preferred way with (better) type safety would be to call `Items.MyDimmer.sendCommand(100)`. Assuming the item in question *actually* is a dimmer, `JRuleDimmerItem.sendCommand(int)` actually wraps the value in a `JRulePercentType`. I have not touched the `JRule.sendCommand()` method which I presume you have tried to use. Maybe they should be deprecated and/or removed?

I think we should update all the examples to use the new way of referring to items?

**Comment by seaside1** [comment]
Thanks, I'll test it out and report back.

**Comment by seaside1** [comment]
Updating I still get:
- No statistics working for java files in folders
- Rules under folders are not loaded 


I would like us to use JRule prefix of all classes in the package, so
Items.java -> JRuleItems.java
DelayedDebouncingExecutor.java -> JRuleDelayedDebouncingExecutor.java

Reason behind this is for users to quickly identify classes defined by the JRule package compared with openhab-core classes.
Also in binding this pattern is used within openhab.
I don't feel strongly about that naming convention but if we want to change it we should probably rename many of the other classes as well.

I agree with update of documentation to use JRuleItems.java, I'll fix it.

**Comment by seaside1** [comment]
I'll try to merge your fixes with main. The symlink fix fixes the issues mentioned above.

/s

**Comment by seaside1** [comment]
I have merged everything now. Hopefully works, will update the docs as well.
